version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - '6379:6379'
  database:
    image: "mysql:8.0.13"
    container_name: mysql-8.0.13
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - '3306:3306'
    volumes:
      - "./mysql:/etc/mysql/conf.d"
  elasticsearch:
    image: "elasticsearch:7.3.2"
    container_name: es-7.3.2
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - "ES_JAVA_POTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
  rabbit:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  mongo:
    image: "mongo:4.0.9"
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0
